server:
  port: 8080
  
spring:
   cloud:
    gateway:
      default-filters:
        - name: LogFilter
      routes:
        - id: apiweatherroute
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/api-catalog/**
        - id: apiusuarioroute
          uri: lb://MOVIE-SERVICE
          predicates:
           - Path=/api-movie/**
