server:
  port: 8080
  
spring:
   cloud:
    gateway:
      routes:
        - id: apiweatherroute
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/catalog/**
        - id: apiusuarioroute
          uri: lb://MOVIE-SERVICE
          predicates:
           - Path=/movie/**
