server:
  port: 8080
  
spring:
   cloud:
    gateway:
      default-filters:
        - name: LogFilter
      routes:
        - id: apiweatherroute
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/api-catalog/**
        - id: apiusuarioroute
          uri: lb://MOVIE-SERVICE
          predicates:
            - Path=/api-movie/**
       


          filters:
            - name: CircuitBreaker
              args:
                name: catalogoCircuitBreaker
                fallbackUri: forward:/catalogo-fallback   
                       
           
message: Gateway porta 8080 > -       
       
