server:
  port: 8080
  
spring:
   cloud:
    gateway:
      default-filters:
        - name: LogFilter
      routes:
        - id: apiweatherroute
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/api-catalog/**
          
          filters:
            - name: CircuitBreaker
              args:
                name: catalogService
                fallbackUri: forward:/fallback/catalog
            
        - id: apiusuarioroute
          uri: lb://MOVIE-SERVICE
          predicates:
            - Path=/api-movie/**
           
# configuraçoes do  Circuit Breaker xxxxxxxxxxxxxxxxxxxx

          filters:
            - name: CircuitBreaker
              args:
                name: movieService
                fallbackUri: forward:/fallback/movie
            
          
       

message: Gateway porta 8080 > -       
       
